#!/usr/bin/env python3
"""Generates the iOS launch images (apple-touch-startup-image) in
assets/launch/ and the matching <link> tags in index.html.

iOS only uses a launch image whose pixel size exactly matches the device's
screen, so there's one per device size (and per color scheme). The logo is
drawn exactly where the loading screen in index.html shows it, so the launch
image, loading screen and app follow each other without a visible jump.

Re-run after changing the logo or adding device sizes:
    python3 tools/generate-launch-images.py
Requires Inkscape (to render logo.svg) and Pillow.
"""
import re
import subprocess
import tempfile
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
LOGO = ROOT / "assets/logo/logo.svg"
OUT = ROOT / "assets/launch"
INDEX = ROOT / "index.html"

# Must match the loading screen styles in index.html
BACKGROUNDS = {"light": "#ffffff", "dark": "#121212"}
LOGO_SIZE = 96  # CSS px
# The loading screen centers logo + gap (2.5rem) + spinner (28px) as a
# group, which puts the logo's center this far above the screen's center.
LOGO_OFFSET = (40 + 28) / 2  # CSS px

# (CSS width, CSS height, device pixel ratio, rotates) in portrait
DEVICES = [
    # iPhones - the app is portrait-only, so no landscape images
    (440, 956, 3, False),  # 16 Pro Max, 17 Pro Max
    (420, 912, 3, False),  # Air
    (402, 874, 3, False),  # 16 Pro, 17, 17 Pro
    (430, 932, 3, False),  # 14 Pro Max, 15 Plus/Pro Max, 16 Plus
    (393, 852, 3, False),  # 14 Pro, 15, 15 Pro, 16
    (428, 926, 3, False),  # 12/13 Pro Max, 14 Plus
    (390, 844, 3, False),  # 12, 13, 14, 16e
    (375, 812, 3, False),  # X, XS, 11 Pro, 12/13 mini
    (414, 896, 3, False),  # XS Max, 11 Pro Max
    (414, 896, 2, False),  # XR, 11
    (414, 736, 3, False),  # 6/7/8 Plus
    (375, 667, 2, False),  # 6/7/8, SE (2nd/3rd gen)
    (320, 568, 2, False),  # SE (1st gen)
    # iPads - these rotate regardless of the manifest's orientation
    (1032, 1376, 2, True),  # iPad Pro 13" (M4)
    (1024, 1366, 2, True),  # iPad Pro 12.9"
    (834, 1210, 2, True),  # iPad Pro 11" (M4)
    (834, 1194, 2, True),  # iPad Pro 11"
    (820, 1180, 2, True),  # iPad Air 10.9"/11", iPad (10th gen)
    (834, 1112, 2, True),  # iPad Air 10.5"
    (810, 1080, 2, True),  # iPad 10.2"
    (768, 1024, 2, True),  # iPad mini (5th gen), iPad 9.7"
    (744, 1133, 2, True),  # iPad mini (6th gen+)
]


def render_logo(pixels, cache={}):
    if pixels not in cache:
        path = Path(tempfile.mkdtemp()) / f"logo-{pixels}.png"
        subprocess.run(
            ["inkscape", str(LOGO), "-w", str(pixels), "-h", str(pixels), "-o", str(path)],
            check=True,
            capture_output=True,
        )
        cache[pixels] = Image.open(path).convert("RGBA")
    return cache[pixels]


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    for old in OUT.glob("*.png"):
        old.unlink()

    links = []
    for width, height, ratio, rotates in DEVICES:
        orientations = [("portrait", width, height)]
        if rotates:
            orientations.append(("landscape", height, width))
        for orientation, css_w, css_h in orientations:
            for scheme, background in BACKGROUNDS.items():
                px_w, px_h = css_w * ratio, css_h * ratio
                image = Image.new("RGBA", (px_w, px_h), background)
                logo = render_logo(LOGO_SIZE * ratio)
                x = (px_w - logo.width) // 2
                y = round(px_h / 2 - LOGO_OFFSET * ratio - logo.height / 2)
                image.alpha_composite(logo, (x, y))

                name = f"launch-{px_w}x{px_h}-{scheme}.png"
                image.convert("RGB").save(OUT / name, optimize=True)
                media = (
                    f"(device-width: {width}px) and (device-height: {height}px) and "
                    f"(-webkit-device-pixel-ratio: {ratio}) and (orientation: {orientation}) and "
                    f"(prefers-color-scheme: {scheme})"
                )
                links.append(
                    f'    <link rel="apple-touch-startup-image" media="{media}" '
                    f'href="assets/launch/{name}" />'
                )

    start, end = "    <!-- launch-images:start -->\n", "    <!-- launch-images:end -->\n"
    block = (
        start
        + "    <!-- Generated by tools/generate-launch-images.py - don't edit by hand -->\n"
        + "\n".join(links)
        + "\n"
        + end
    )
    html = INDEX.read_text()
    if start in html:
        html = re.sub(re.escape(start) + ".*?" + re.escape(end), lambda _: block, html, flags=re.S)
    else:
        anchor = '    <link rel="manifest" href="manifest.json" />\n'
        html = html.replace(anchor, block + anchor)
    INDEX.write_text(html)
    print(f"{len(links)} launch images written to {OUT.relative_to(ROOT)}/")


if __name__ == "__main__":
    main()
